name: Terraform CI

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      # 0) Detecta se há credenciais (sem usar secrets no "if")
      - name: Detect AWS creds
        id: detect-creds
        env:
          AKID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          SAK:  ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          if [ -n "${AKID}" ] && [ -n "${SAK}" ]; then
            echo "has_creds=true"  >> $GITHUB_OUTPUT
          else
            echo "has_creds=false" >> $GITHUB_OUTPUT
          fi

      # 1) fmt
      - name: Terraform fmt (check)
        run: terraform fmt -check -diff

      # 2) init
      - name: Terraform init
        run: terraform init -input=false

      # 3) validate
      - name: Terraform validate
        run: terraform validate

      # 4) Configura credenciais (só se detectou)
      - name: Configure AWS credentials
        if: ${{ steps.detect-creds.outputs.has_creds == 'true' }}
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # 5) plan (opcional; só se detectou)
      - name: Terraform plan
        if: ${{ steps.detect-creds.outputs.has_creds == 'true' }}
        env:
          TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
        run: terraform plan -input=false -out=tfplan

      # 6) upload do plano (opcional; só se detectou)
      - name: Upload plan artifact
        if: ${{ steps.detect-creds.outputs.has_creds == 'true' }}
        uses: actions/upload-artifact@v4
        with:
          name: tfplan
          path: terraform/tfplan

      # 7) apply automático (apenas na main e se tiver credenciais)
      - name: Terraform apply
        if: ${{ github.ref == 'refs/heads/main' && steps.detect-creds.outputs.has_creds == 'true' }}
        env:
          TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}
        run: terraform apply -input=false -auto-approve tfplan
